import type { Conference, Webinar, MasterClass } from "@/entities/announcement/model/index"

export const mockUserAnnouncements: Array<(Conference | Webinar | MasterClass) & { id: string }> = [
  {
    id: "conf-stages-1",
    type: "Conference",
    title: "Международная конференция по кардиологии 2025",
    description:
      "Ведущие кардиологи мира представят последние достижения в области диагностики и лечения сердечно-сосудистых заболеваний. Обсуждение инновационных методов лечения, новых препаратов и технологий.",
    organizerName: "Российское кардиологическое общество",
    organizerId: "543534553",
    activeFrom: "2025-11-29",
    activeTo: "2025-12-17",
    status: "published",
    location: {
      address: 'Конгресс-холл "Крокус Экспо"',
      city: "Москва",
    },
    format: "offline",
    contactInfo: {
      email: "info@cardio-conf.ru",
      phone: "+7 (495) 123-45-67",
      website: "https://cardio-conf.ru",
    },
    tags: ["кардиология", "медицина", "конференция", "инновации"],
    viewsCount: 1250,
    isPromoted: true,
    createdAt: "2025-09-15T10:00:00Z",
    updatedAt: "2025-09-01T15:30:00Z",
    speakers: [
      {
        userId: "speaker-1",
        name: "Профессор Иванов А.В.",
        eventRole: "Главный докладчик",
        status: "confirmed",
      },
      {
        userId: "speaker-2",
        name: "Доктор Петрова М.С.",
        eventRole: "Модератор секции",
        status: "confirmed",
      },
    ],
    program: "День 1: Диагностика ИБС\nДень 2: Современные методы лечения\nДень 3: Профилактика и реабилитация",
    registrationRequired: true,
    registrationLink: "https://cardio-conf.ru/register",
    maxParticipants: 500,
    price_type: "paid",
    currentParticipants: 342,
    price: 15000,
    currency: "RUB",
    categories: ["medical"],
    targetAudience: ["doctors", "specialists", "students", "researchers"],
    language: "ru",
    certificates: true,
    cmeCredits: 24,
    previewImage: "/1.png"
  },
  {
    id: "conf-no-stages-1",
    type: "Webinar",
    title: "Основы машинного обучения в медицине",
    description:
      "Практический вебинар для медицинских работников о применении машинного обучения в диагностике. Разберем реальные кейсы использования ИИ в радиологии и патологии.",
    organizerName: "AI Medical Academy",
    organizerId: "5435343",
    activeFrom: "2025-12-25",
    status: "published",
    format: "online",
    contactInfo: {
      email: "support@aimedacademy.ru",
      website: "https://aimedacademy.ru",
    },
    tags: ["машинное обучение", "ИИ", "медицина", "диагностика"],
    viewsCount: 567,
    isPromoted: false,
    createdAt: "2025-09-01T12:00:00Z",
    updatedAt: "2025-09-15T16:45:00Z",
    speakers: [
      {
        userId: "speaker-4",
        name: "Кандидат наук Сидоров В.П.",
        eventRole: "Ведущий эксперт",
        status: "confirmed",
      },
    ],
    platform: "zoom",
    platformDetails: {
      meetingId: "123-456-789",
      joinUrl: "https://zoom.us/j/123456789",
    },
    isRecorded: true,
    recordingAvailableUntil: "2025-09-25",
    participantLimit: 100,
    registrationLink: "https://aimedacademy.ru/webinar-ml",
    price_type: "paid",
    price: 3000,
    currency: "RUB",
    categories: ["medical", "it"],
    targetAudience: ["doctors", "specialists"],
    language: "ru",
    duration: 120,
    prerequisites: "Базовые знания статистики и работы с компьютером",
    materials: ["Презентация", "Практические задания", "Список литературы"],
    previewImage: "/3.png"
  },
  {
    id: "masterclass-1",
    type: "Masterclass",
    title: "Практический курс по УЗИ сердца",
    description:
      "Интенсивный практический мастер-класс по эхокардиографии. Отработка навыков на современном оборудовании под руководством опытных специалистов.",
    organizerName: 'Центр ультразвуковой диагностики "Эксперт"',
    organizerId: "543fs",
    activeFrom: "2025-11-30",
    activeTo: "2025-12-31",
    status: "published",
    location: {
      address: 'Учебный центр "МедПрактик"',
      city: "Москва",
    },
    format: "offline",
    contactInfo: {
      email: "masterclass@uzi-expert.ru",
      phone: "+7 (495) 555-12-34",
      website: "https://uzi-expert.ru",
    },
    tags: ["УЗИ", "эхокардиография", "практика", "диагностика"],
    viewsCount: 234,
    isPromoted: false,
    createdAt: "2025-09-25T13:15:00Z",
    updatedAt: "2025-09-12T10:30:00Z",
    instructor: {
      userId: "instructor-1",
      name: "Доктор медицинских наук Волков А.И.",
      bio: "Ведущий специалист по ультразвуковой диагностике, стаж 20+ лет",
      credentials: ["Доктор медицинских наук", "Профессор кафедры лучевой диагностики"],
    },
    skillLevel: "intermediate",
    maxParticipants: 12,
    currentParticipants: 8,
    registrationLink: "https://endocrin.ru/webinar-diabetes",
    price_type: "paid",
    price: 35000,
    currency: "RUB",
    materials: ["Методические пособия", "Атлас УЗИ-изображений"],
    equipment: ["УЗИ-аппараты экспертного класса", "Фантомы для обучения"],
    duration: 16,
    categories: ["medical"],
    prerequisites: "Медицинское образование, базовые знания УЗИ",
    certificates: true,
    handsOn: true,
    groupWork: true,
    previewImage: "/5.png"
  },
]
