import type { Conference, Webinar, MasterClass, Vacancy, Olympiad } from "./index"

export const mockConferences: (Conference & { id: string })[] = [
  {
    id: "conf-2",
    type: "Conference",
    title: "Цифровые технологии в современной медицине",
    description: `ПРЕДСТАВЛЕНИЕ ДАННЫХ И ЗНАНИЙ В ЗДРАВООХРАНЕНИИ
  ✓ представление данных и знаний в здравоохранении;
  ✓ обмен медицинскими данными;
  ✓ цифровые двойники в здравоохранении;
  ✓ моделирование в здравоохранении;
  ✓ применение методов искусственного интеллекта и математических методов для обработки медицинских данных и знаний.

────────────────────────────────────────
ПРИМЕНЕНИЕ ТЕЛЕМЕДИЦИНСКИХ ТЕХНОЛОГИЙ ПРИ ОКАЗАНИИ МЕДИЦИНСКОЙ ПОМОЩИ
  ✓ использование телемедицинских технологий для диагностики, мониторинга и консультирования.

────────────────────────────────────────
КОМПЬЮТЕРНАЯ ИНЖЕНЕРИЯ
  ✓ обработка сигналов медицинских устройств;
  ✓ научное обоснование возможностей робототехники и формирование требований к робототехническим системам;
  ✓ компьютерная инженерия;
  ✓ нейроинформатика и нейроинженерия.

────────────────────────────────────────
ОРГАНИЗАЦИЯ ПРИМЕНЕНИЯ И УПРАВЛЕНИЕ ПРИМЕНЕНИЕМ ЦИФРОВЫХ ТЕХНОЛОГИЙ В ЗДРАВООХРАНЕНИИ
  ✓ стандартизация и нормативно-правовое обеспечение цифровой медицины;
  ✓ организация применения и управление внедрением цифровых технологий в здравоохранении;
  ✓ анализ влияния цифровых технологий на деятельность медработников и оценка рисков их негативного влияния на эффективность лечебного процесса;
  ✓ оценка эффекта от внедрения цифровых технологий в практическое здравоохранение (медицинский, социальный, экономический).
`,
    organizerName: "Центр цифровой медицины Сеченовского Университета, Дирекция проектов ИТМ ",
    organizerId: "543534df",
    activeFrom: "2025-10-09",
    activeTo: "2025-10-10",
    status: "published",
    location: {
      address: '129329, г. Москва, ул. Кольская, д. 2, корп. 6, офис 703',
      city: "Москва",
    },
    format: "offline",
    contactInfo: {
      email: "med@consef.ru",
      phone: "+74959782511",
    },
    tags: ["цифровая медицина", "цифровые технологии в современной медицине", "инновации"],
    viewsCount: 890,
    isPromoted: true,
    createdAt: "2025-09-01T14:00:00Z",
    updatedAt: "2025-09-01T14:00:00Z",
    speakers: [
      {
        userId: "speaker-1",
        name: "проф. Георгий Лебедев",
        eventRole: "Сопредседатель",
        bio: "Институт цифровой медицины ПМГМУ им. И.М. Сеченова, Москва. Директор, зав. кафедрой информационных и интернет-технологий, д.т.н.",
        status: "confirmed",
      },
      {
        userId: "speaker-2",
        name: "Игорь Шадеркин",
        eventRole: "Сопредседатель",
        bio: "Сеченовский университет, Москва. Руководитель проекта Цифровая кафедра, к.м.н.",
        status: "confirmed",
      },
      {
        userId: "speaker-3",
        name: "проф. Филипп Копылов",
        eventRole: "Сопредседатель",
        bio: "Сеченовский университет, Москва. Директор института персонализированной кардиологии, д.м.н.",
        status: "confirmed",
      },
      {
        userId: "speaker-4",
        name: "Анна Баврина",
        eventRole: "Сопредседатель",
        bio: "Приволжский исследовательский медицинский университет, Нижний Новгород. Доцент, зав. кафедрой информационных технологий, к.б.н.",
        status: "confirmed",
      },
      {
        userId: "speaker-5",
        name: "проф. Елена Бородулина",
        eventRole: "Спикер",
        bio: "Самарский государственный медицинский университет, Самара. Зав. кафедрой фтизиатрии и пульмонологии, д.м.н.",
        status: "confirmed",
      },
      {
        userId: "speaker-6",
        name: "Ольга Буркова",
        eventRole: "Ответственный секретарь",
        bio: "Сеченовский университет, Москва. Специалист по учебно-методической работе Цифровой кафедры.",
        status: "confirmed",
      },
      {
        userId: "speaker-7",
        name: "Галия Закирьянова",
        eventRole: "Спикер",
        bio: "Башкирский государственный медицинский университет, Уфа. И.о. зав. кафедрой медицинской физики и информатики, к.ф.-м.н., доцент.",
        status: "confirmed",
      },
      {
        userId: "speaker-8",
        name: "Герман Клименко",
        eventRole: "Спикер",
        bio: "Сеченовский университет, Москва. Старший преподаватель кафедры информационных и интернет-технологий.",
        status: "confirmed",
      },
      {
        userId: "speaker-9",
        name: "Юрий Мухин",
        eventRole: "Спикер",
        bio: "#ИТМ / Информационные ресурсы для цифрового здравоохранения. Программный директор, к.э.н.",
        status: "confirmed",
      },
      {
        userId: "speaker-10",
        name: "проф. Чавдар Павлов",
        eventRole: "Спикер",
        bio: "Сеченовский университет, Москва. Зам. директора института клинической медицины им. Н.В. Склифосовского, д.м.н.",
        status: "confirmed",
      },
      {
        userId: "speaker-11",
        name: "проф. Игорь Решетов",
        eventRole: "Спикер",
        bio: "Институт кластерной онкологии им. профессора П.Л. Левшина, Москва. Директор, д.м.н., академик РАН.",
        status: "confirmed",
      },
      {
        userId: "speaker-12",
        name: "Сергей Соколов",
        eventRole: "Спикер",
        bio: "Уральский государственный медицинский университет, Екатеринбург. Зав. кафедрой медицинской физики и цифровых технологий, к.ф.-м.н., доцент.",
        status: "confirmed",
      },
      {
        userId: "speaker-13",
        name: "Эдуард Фартушный",
        eventRole: "Спикер",
        bio: "Сеченовский университет, Москва. Зам. директора Центра цифровой медицины.",
        status: "confirmed",
      },
      {
        userId: "speaker-14",
        name: "проф. Олег Чопоров",
        eventRole: "Спикер",
        bio: "Воронежский государственный медицинский университет им. Н.Н. Бурденко. Проректор по цифровой трансформации, д.т.н.",
        status: "confirmed",
      },
      {
        userId: "speaker-15",
        name: "Антон Шафрай",
        eventRole: "Спикер",
        bio: "Кемеровский государственный университет, Кемерово. Зав. кафедрой «Инженерный дизайн», к.т.н., доцент.",
        status: "confirmed",
      },
    ],
    program: "ЭТАПЫ РАССМОТРЕНИЯ ЗАЯВОК, ПРЕДВАРИТЕЛЬНОГО ОТБОРА И ДОРАБОТКИ ПРОЕКТОВ\n\nЭТАП ПОДАЧИ ЗАЯВОК И ПРОЕКТОВ\n1 июля – 19 сентября 2025 г.\n\nЭТАП РЕЦЕНЗИРОВАНИЯ И ДОРАБОТКИ ПРОЕКТОВ\n19 сентября – 3 октября 2025 г.\n\nПОДВЕДЕНИЕ ИТОГОВ И ОТБОР ЛУЧШИХ ПРОЕКТОВ\n3 октября 2025 г.\n\nПОДВЕДЕНИЕ ИТОГОВ, ПРЕЗЕНТАЦИЯ И НАГРАЖДЕНИЕ\n10 октября 2025 г., 13:00 – 15:00",
    //\nXXVI Ежегодный Международный конгресс «Информационные технологии в медицине» (ИТМ2025)\nЗал «Галактика Центральная», конгресс-центр гостиницы «Космос»\nМосква, проспект Мира, 150
    registrationRequired: true,
    registrationLink: "https://itmcongress.ru/Sechenov/",
    price_type: "free",
    currentParticipants: 156,
    price: 0,
    currency: "RUB",
    categories: ["medical", "it"],
    targetAudience: ["doctors", "students", 'general'],
    language: "ru",
    certificates: true,
    cmeCredits: 16,
    previewImage: "/6.png"
  },
  {
    id: "conf-1",
    type: "Conference",
    title: "Международная конференция по кардиологии 2025",
    description:
      "Ведущие кардиологи мира представят последние достижения в области диагностики и лечения сердечно-сосудистых заболеваний. Обсуждение инновационных методов лечения, новых препаратов и технологий.",
    organizerName: "Российское кардиологическое общество",
    organizerId: "543534553",
    activeFrom: "2025-11-29",
    activeTo: "2025-12-17",
    status: "published",
    location: {
      address: 'Конгресс-холл "Крокус Экспо"',
      city: "Москва",
    },
    format: "offline",
    contactInfo: {
      email: "info@cardio-conf.ru",
      phone: "+7 (495) 123-45-67",
      website: "https://cardio-conf.ru",
    },
    tags: ["кардиология", "медицина", "конференция", "инновации"],
    viewsCount: 1250,
    isPromoted: true,
    createdAt: "2025-09-15T10:00:00Z",
    updatedAt: "2025-09-01T15:30:00Z",
    speakers: [
      {
        userId: "speaker-1",
        name: "Профессор Иванов А.В.",
        eventRole: "Главный докладчик",
        status: "confirmed",
      },
      {
        userId: "speaker-2",
        name: "Доктор Петрова М.С.",
        eventRole: "Модератор секции",
        status: "confirmed",
      },
    ],
    program: "День 1: Диагностика ИБС\nДень 2: Современные методы лечения\nДень 3: Профилактика и реабилитация",
    registrationRequired: true,
    registrationLink: "https://cardio-conf.ru/register",
    maxParticipants: 500,
    price_type: "paid",
    currentParticipants: 342,
    price: 15000,
    currency: "RUB",
    categories: ["medical"],
    targetAudience: ["doctors", "specialists", "students", "researchers"],
    language: "ru",
    certificates: true,
    cmeCredits: 24,
    previewImage: "/1.png"
  },
  {
    id: "conf-3",
    type: "Conference",
    title: "Саммит цифрового здравоохранения 2025",
    description:
      "Международный саммит по цифровому здравоохранению. Обсуждение применения ИИ в медицине, телемедицины, цифровых биомаркеров и персонализированной медицины.",
    organizerName: "TechMed International",
    organizerId: "543534553gdf",
    activeFrom: "2025-10-20",
    activeTo: "2025-11-21",
    status: "published",
    location: {
      address: 'Отель "Метрополь"',
      city: "Санкт-Петербург",
    },
    format: "hybrid",
    contactInfo: {
      email: "contact@digitalhealthsummit.com",
      website: "https://digitalhealthsummit.com",
    },
    tags: ["цифровая медицина", "ИИ", "телемедицина", "инновации"],
    viewsCount: 890,
    isPromoted: false,
    createdAt: "2025-09-20T14:00:00Z",
    updatedAt: "2025-10-10T09:15:00Z",
    speakers: [
      {
        userId: "speaker-3",
        name: "Dr. Sarah Johnson",
        eventRole: "Ключевой докладчик",
        status: "confirmed",
      },
    ],
    program: "ИИ в здравоохранении, тренды телемедицины, цифровые биомаркеры",
    registrationRequired: true,
    registrationLink: "https://digitalhealthsummit.com/register",
    maxParticipants: 300,
    price_type: "free",
    currentParticipants: 156,
    price: 25000,
    currency: "RUB",
    categories: ["medical", "it"],
    targetAudience: ["doctors", "specialists", "researchers"],
    language: "multi",
    certificates: true,
    cmeCredits: 16,
    previewImage: "/2.png"
  },
]

export const mockWebinars: (Webinar & { id: string })[] = [
  {
    id: "webinar-1",
    type: "Webinar",
    title: "Основы машинного обучения в медицине",
    description:
      "Практический вебинар для медицинских работников о применении машинного обучения в диагностике. Разберем реальные кейсы использования ИИ в радиологии и патологии.",
    organizerName: "AI Medical Academy",
    organizerId: "5435343",
    activeFrom: "2025-12-25",
    status: "published",
    format: "online",
    contactInfo: {
      email: "support@aimedacademy.ru",
      website: "https://aimedacademy.ru",
    },
    tags: ["машинное обучение", "ИИ", "медицина", "диагностика"],
    viewsCount: 567,
    isPromoted: true,
    createdAt: "2025-09-01T12:00:00Z",
    updatedAt: "2025-09-15T16:45:00Z",
    speakers: [
      {
        userId: "speaker-4",
        name: "Кандидат наук Сидоров В.П.",
        eventRole: "Ведущий эксперт",
        status: "confirmed",
      },
    ],
    platform: "zoom",
    platformDetails: {
      meetingId: "123-456-789",
      joinUrl: "https://zoom.us/j/123456789",
    },
    isRecorded: true,
    recordingAvailableUntil: "2025-09-25",
    participantLimit: 100,
    registrationLink: "https://aimedacademy.ru/webinar-ml",
    price_type: "paid",
    price: 3000,
    currency: "RUB",
    categories: ["medical", "it"],
    targetAudience: ["doctors", "specialists"],
    language: "ru",
    duration: 120,
    prerequisites: "Базовые знания статистики и работы с компьютером",
    materials: ["Презентация", "Практические задания", "Список литературы"],
    previewImage: "/3.png"
  },
  {
    id: "webinar-2",
    type: "Webinar",
    title: "Современные подходы к лечению диабета",
    description:
      "Обзор новейших методов лечения сахарного диабета 2 типа. Обсуждение персонализированной терапии, новых препаратов и технологий мониторинга.",
    organizerName: "Эндокринологическое общество России",
    organizerId: "534553",
    activeFrom: "2025-10-10",
    status: "published",
    format: "online",
    contactInfo: {
      email: "webinars@endocrin.ru",
      phone: "+7 (495) 987-65-43",
    },
    tags: ["диабет", "эндокринология", "лечение", "инновации"],
    viewsCount: 423,
    isPromoted: false,
    createdAt: "2025-09-05T09:30:00Z",
    updatedAt: "2025-09-20T11:20:00Z",
    speakers: [
      {
        userId: "speaker-5",
        name: "Профессор Козлова Е.А.",
        eventRole: "Главный эксперт",
        status: "confirmed",
      },
    ],
    platform: "teams",
    isRecorded: true,
    recordingLink: "https://endocrin.ru/recordings/diabetes-2025",
    recordingAvailableUntil: "2025-09-10",
    participantLimit: 200,
    registrationLink: "https://endocrin.ru/webinar-diabetes",
    price_type: "free",
    price: 0,
    currency: "RUB",
    categories: ["medical"],
    targetAudience: ["doctors", "specialists"],
    language: "ru",
    duration: 90,
    prerequisites: "Медицинское образование",
    materials: ["Клинические рекомендации", "Алгоритмы лечения"],
    previewImage: "/4.png"
  },
]

export const mockMasterClasses: (MasterClass & { id: string })[] = [
  {
    id: "masterclass-1",
    type: "Masterclass",
    title: "Практический курс по УЗИ сердца",
    description:
      "Интенсивный практический мастер-класс по эхокардиографии. Отработка навыков на современном оборудовании под руководством опытных специалистов.",
    organizerName: 'Центр ультразвуковой диагностики "Эксперт"',
    organizerId: "543fs",
    activeFrom: "2025-11-30",
    activeTo: "2025-12-31",
    status: "published",
    location: {
      address: 'Учебный центр "МедПрактик"',
      city: "Москва",
    },
    format: "offline",
    contactInfo: {
      email: "masterclass@uzi-expert.ru",
      phone: "+7 (495) 555-12-34",
      website: "https://uzi-expert.ru",
    },
    tags: ["УЗИ", "эхокардиография", "практика", "диагностика"],
    viewsCount: 234,
    isPromoted: true,
    createdAt: "2025-09-25T13:15:00Z",
    updatedAt: "2025-09-12T10:30:00Z",
    instructor: {
      userId: "instructor-1",
      name: "Доктор медицинских наук Волков А.И.",
      bio: "Ведущий специалист по ультразвуковой диагностике, стаж 20+ лет",
      credentials: ["Доктор медицинских наук", "Профессор кафедры лучевой диагностики"],
    },
    skillLevel: "intermediate",
    maxParticipants: 12,
    currentParticipants: 8,
    registrationLink: "https://endocrin.ru/webinar-diabetes",
    price_type: "paid",
    price: 35000,
    currency: "RUB",
    materials: ["Методические пособия", "Атлас УЗИ-изображений"],
    equipment: ["УЗИ-аппараты экспертного класса", "Фантомы для обучения"],
    duration: 16,
    categories: ["medical"],
    prerequisites: "Медицинское образование, базовые знания УЗИ",
    certificates: true,
    handsOn: true,
    groupWork: true,
    previewImage: "/5.png"
  },
  {
    id: "masterclass-2",
    type: "Masterclass",
    title: "Практический курс по лапароскопической хирургии",
    description:
      "Интенсивный мастер-класс с отработкой базовых лапароскопических навыков на тренажёрах: работа инструментами в ограниченном пространстве, координация «глаз–рука», наложение внутриполостных узлов, гемостаз и разбор типичных осложнений.",
    organizerName: 'Симуляционный центр клинических навыков "МедСим"',
    organizerId: "5213563",
    activeFrom: "2025-10-15",
    activeTo: "2025-11-16",
    status: "published",
    location: {
      address: 'Симуляционный центр "МедСим"',
      city: "Москва",
    },
    format: "offline",
    contactInfo: {
      email: "training@medsim.ru",
      website: "https://medsim.ru",
    },
    tags: ["лапароскопия", "хирургия", "симуляционный тренинг", "операционный блок"],
    viewsCount: 189,
    isPromoted: false,
    createdAt: "2025-09-10T11:45:00Z",
    updatedAt: "2025-09-25T14:20:00Z",
    instructor: {
      userId: "instructor-2",
      name: "К.м.н. Николаев М.А.",
      bio: "Лапароскопический хирург, 8+ лет операционного стажа, преподаватель симуляционного тренинга",
      credentials: ["Кандидат медицинских наук", "Врач-хирург высшей категории"],
    },
    speakers: [
      {
        userId: "speaker-6",
        name: "Профессор Смирнов А.А.",
        eventRole: "Приглашённый эксперт",
        status: "confirmed",
      },
      {
        userId: "speaker-7",
        name: "Орлова Н.В.",
        eventRole: "Эксперт по анестезиологии и ERAS",
        status: "pending",
      },
    ],
    skillLevel: "intermediate",
    maxParticipants: 16,
    currentParticipants: 12,
    registrationLink: "https://medsim.ru/courses/laparoscopic-skills",
    price_type: "paid",
    price: 25000,
    currency: "RUB",
    materials: ["Методическое пособие", "Чек-листы навыков", "Видеозаписи операций"],
    equipment: [
      "Лапароскопические тренажёры (box trainer)",
      "Видеостойка",
      "Набор лапароскопических инструментов",
      "Электрохирургический симулятор",
    ],
    duration: 16,
    categories: ["medical"],
    prerequisites: "Хирургическое образование или обучение в ординатуре по хирургии",
    certificates: true,
    handsOn: true,
    groupWork: true,
    previewImage: "/1.png"
  },
]

export const mockVacancies: (Vacancy & { id: string })[] = [
  {
    id: "vacancy-1",
    type: "Vacancy",
    title: "Врач-кардиолог",
    description:
      "Ищем опытного врача-кардиолога для работы в современной клинике. Предлагаем стабильную работу, достойную заработную плату и возможности профессионального развития.",
    organizerName: 'Медицинский центр "Кардио+"',
    organizerId: "org-cardio-1",
    activeFrom: "2025-09-01",
    activeTo: "2025-10-30",
    status: "published",
    location: {
      address: "ул. Медицинская, 15",
      city: "Москва",
    },
    contactInfo: {
      email: "hr@cardioplus.ru",
      phone: "+7 (495) 123-45-67",
      website: "https://cardioplus.ru",
    },
    tags: ["кардиология", "врач", "медицина", "полная занятость"],
    viewsCount: 456,
    isPromoted: true,
    createdAt: "2025-09-15T10:00:00Z",
    updatedAt: "2025-09-20T15:30:00Z",
    position: "Врач-кардиолог",
    department: "Кардиологическое отделение",
    employmentType: "full-time",
    workFormat: "office",
    salary: {
      min: 120000,
      max: 180000,
      currency: "RUB",
      negotiable: true,
    },
    requirements: {
      education: "Высшее медицинское образование, специализация по кардиологии",
      experience: "Опыт работы врачом-кардиологом от 3 лет",
      skills: [
        "Диагностика сердечно-сосудистых заболеваний",
        "ЭКГ, ЭхоКГ",
        "Холтеровское мониторирование",
        "Стресс-тесты",
        "Работа с медицинской документацией",
      ],
      certifications: ["Сертификат специалиста по кардиологии"],
      languages: ["Русский (свободно)", "Английский (базовый)"],
    },
    responsibilities: [
      "Консультирование пациентов с заболеваниями сердечно-сосудистой системы",
      "Проведение диагностических исследований",
      "Назначение и контроль лечения",
      "Ведение медицинской документации",
      "Участие в консилиумах и медицинских советах",
    ],
    benefits: [
      "Официальное трудоустройство",
      "ДМС для сотрудника и семьи",
      "Оплачиваемое обучение и повышение квалификации",
      "Современное оборудование",
      "Дружный коллектив",
      "Гибкий график работы",
    ],
    schedule: "5/2, с 9:00 до 18:00",
    hiringManager: {
      name: "Петрова Анна Сергеевна",
      position: "HR-менеджер",
      photo: "/placeholder-avatar.jpg",
    },
    applicationDeadline: "2025-09-30",
    categories: ["medical"],
    urgent: false,
    featured: false,
    previewImage: "/2.png"
  },
  {
    id: "vacancy-2",
    type: "Vacancy",
    title: "Медицинская сестра в отделение реанимации",
    description:
      "Приглашаем на работу опытную медицинскую сестру в отделение реанимации и интенсивной терапии. Работа в команде профессионалов, современное оборудование, достойная оплата труда.",
    organizerName: "Городская клиническая больница №1",
    organizerId: "org-hospital-1",
    activeFrom: "2025-09-05",
    activeTo: "2025-11-05",
    status: "published",
    location: {
      address: "пр. Ленина, 45",
      city: "Екатеринбург",
    },
    contactInfo: {
      email: "kadry@gkb1.ru",
      phone: "+7 (343) 555-12-34",
    },
    tags: ["медсестра", "реанимация", "интенсивная терапия", "больница"],
    viewsCount: 189,
    isPromoted: false,
    createdAt: "2025-09-28T11:30:00Z",
    updatedAt: "2025-09-02T16:45:00Z",
    position: "Медицинская сестра",
    department: "Отделение реанимации и интенсивной терапии",
    employmentType: "full-time",
    workFormat: "office",
    salary: {
      min: 45000,
      max: 65000,
      currency: "RUB",
      negotiable: false,
    },
    requirements: {
      education: "Среднее профессиональное медицинское образование",
      experience: "Опыт работы медицинской сестрой от 1 года, желательно в реанимации",
      skills: [
        "Навыки работы с реанимационным оборудованием",
        "Внутривенные инъекции и инфузии",
        "Уход за тяжелобольными пациентами",
        "Мониторинг жизненных показателей",
        "Работа с медицинской документацией",
      ],
      certifications: ["Сертификат медицинской сестры", "Курсы по реанимации (желательно)"],
    },
    responsibilities: [
      "Уход за пациентами в критическом состоянии",
      "Выполнение назначений врача",
      "Мониторинг состояния пациентов",
      "Работа с медицинским оборудованием",
      "Ведение сестринской документации",
      "Соблюдение санитарно-эпидемиологического режима",
    ],
    benefits: [
      "Стабильная заработная плата",
      "Социальный пакет",
      "Повышение квалификации за счет работодателя",
      "Дополнительный отпуск медработникам",
      "Льготы по ДМС",
    ],
    schedule: "Сменный график 12/12",
    hiringManager: {
      name: "Козлова Елена Викторовна",
      position: "Старшая медицинская сестра ОРИТ",
    },
    categories: ["medical"],
    urgent: false,
    featured: false,
    previewImage: "/3.png"
  },
]

export const mockOlympiads: (Olympiad & { id: string })[] = [
  {
    id: "olympiad-1",
    type: "Olimpiad",
    title: "Всероссийская олимпиада по анатомии человека",
    description:
      "Престижная олимпиада для студентов медицинских вузов по анатомии человека. Включает теоретический и практический туры с использованием анатомических препаратов и муляжей.",
    organizerName: "Российская ассоциация медицинского образования",
    organizerId: "org-rame-1",
    activeFrom: "2025-09-15",
    activeTo: "2025-09-17",
    status: "published",
    location: {
      address: "Первый МГМУ им. И.М. Сеченова",
      city: "Москва",
    },
    contactInfo: {
      email: "olympiad@sechenov.ru",
      phone: "+7 (495) 609-14-00",
      website: "https://sechenov.ru/olympiad",
    },
    tags: ["анатомия", "медицина", "олимпиада", "студенты"],
    viewsCount: 892,
    isPromoted: true,
    createdAt: "2025-09-10T09:00:00Z",
    updatedAt: "2025-09-15T14:30:00Z",
    olympiadLevel: "national",
    competitionFormat: "individual",
    subjects: ["anatomy", "histology", "embryology"],
    eligibility: {
      educationLevel: "medical_undergraduate",
      yearsAllowed: { min: 2, max: 6 },
      specialtiesAllowed: ["Лечебное дело", "Педиатрия", "Стоматология"],
      prerequisites: ["Завершенный курс нормальной анатомии"],
    },
    rounds: [
      {
        name: "Отборочный тур",
        stage: "qualifier",
        mode: "online",
        dateFrom: "2025-09-01",
        dateTo: "2025-09-15",
        subjects: ["anatomy"],
        examKinds: ["mcq"],
        durationMinutes: 120,
        weightPercent: 40,
        proctoring: "online_proctoring",
        description: "Тестирование по общим вопросам анатомии",
      },
      {
        name: "Финальный тур",
        stage: "final",
        mode: "offline",
        dateFrom: "2025-09-15",
        dateTo: "2025-09-17",
        subjects: ["anatomy", "histology", "embryology"],
        examKinds: ["practical", "osce"],
        durationMinutes: 180,
        weightPercent: 60,
        proctoring: "in_person_proctoring",
        description: "Практическая работа с препаратами и микроскопией",
      },
    ],
    scoring: {
      ranking: "individual",
      totalPoints: 100,
      passingScore: 60,
      tieBreakers: ["Результат финального тура", "Возраст участника"],
    },
    awards: [
      {
        type: "gold",
        title: "Диплом I степени",
        details: "Золотая медаль и денежная премия",
        monetaryAmount: 50000,
        currency: "RUB",
      },
      {
        type: "silver",
        title: "Диплом II степени",
        details: "Серебряная медаль и денежная премия",
        monetaryAmount: 30000,
        currency: "RUB",
      },
      {
        type: "bronze",
        title: "Диплом III степени",
        details: "Бронзовая медаль и денежная премия",
        monetaryAmount: 20000,
        currency: "RUB",
      },
      {
        type: "certificate",
        title: "Сертификат участника",
        details: "Всем участникам финального тура",
      },
    ],
    maxParticipants: 200,
    currentParticipants: 156,
    registrationRequired: true,
    registrationLink: "https://sechenov.ru/olympiad/register",
    registrationOpenAt: "2025-10-01",
    registrationCloseAt: "2025-11-28",
    documentsRequired: ["Справка о зачислении", "Студенческий билет", "Паспорт"],
    price_type: "free",
    price: 0,
    currency: "RUB",
    hostOrganization: "Первый МГМУ им. И.М. Сеченова",
    venueName: "Анатомический театр",
    jury: [
      {
        name: "Профессор Иванов А.В.",
        role: "Председатель жюри",
        affiliation: "Первый МГМУ им. И.М. Сеченова",
      },
      {
        name: "Доцент Петрова М.С.",
        role: "Член жюри",
        affiliation: "РНИМУ им. Н.И. Пирогова",
      },
    ],
    logistics: {
      accommodationProvided: true,
      travelReimbursed: "partial",
      mealsProvided: true,
      notes: "Размещение в общежитии университета для иногородних участников",
    },
    docs: {
      rulesUrl: "https://sechenov.ru/olympiad/rules.pdf",
      syllabusUrl: "https://sechenov.ru/olympiad/syllabus.pdf",
      scheduleUrl: "https://sechenov.ru/olympiad/schedule.pdf",
    },
    categories: ["medical", "educational"],
    targetAudience: ["students"],
    language: "ru",
    level: "Всероссийская",
    participationFormat: "Индивидуальное",
    registrationDeadline: "2025-09-28",
    registrationFee: 0,
    previewImage: "/4.png"
  },
  {
    id: "olympiad-2",
    type: "Olimpiad",
    title: "Международная олимпиада по клинической медицине",
    description:
      "Престижная международная олимпиада для студентов старших курсов и ординаторов. Включает решение клинических кейсов, практические навыки и командные соревнования.",
    organizerName: "Международная ассоциация медицинского образования",
    organizerId: "org-iame-1",
    activeFrom: "2025-09-20",
    activeTo: "2025-09-24",
    status: "published",
    location: {
      address: "Медицинский университет",
      city: "Санкт-Петербург",
    },
    contactInfo: {
      email: "info@medical-olympiad.org",
      website: "https://medical-olympiad.org",
    },
    tags: ["клиническая медицина", "международная олимпиада", "кейсы", "OSCE"],
    viewsCount: 1247,
    isPromoted: true,
    createdAt: "2025-09-20T11:00:00Z",
    updatedAt: "2025-09-25T16:45:00Z",
    olympiadLevel: "international",
    competitionFormat: "both",
    subjects: ["internal_medicine", "surgery", "pediatrics", "first_aid"],
    teamRules: {
      minSize: 3,
      maxSize: 4,
      sameInstitutionRequired: true,
      supervisorRequired: true,
      notes: "Команда должна включать студентов разных курсов",
    },
    eligibility: {
      educationLevel: "mixed",
      yearsAllowed: { min: 4, max: 6 },
      specialtiesAllowed: ["Лечебное дело", "Педиатрия"],
      ageMax: 28,
      prerequisites: ["Завершенные курсы пропедевтики и внутренних болезней"],
    },
    rounds: [
      {
        name: "Индивидуальный тур",
        stage: "qualifier",
        mode: "offline",
        dateFrom: "2025-09-20",
        subjects: ["internal_medicine", "surgery"],
        examKinds: ["case", "mcq"],
        durationMinutes: 150,
        weightPercent: 30,
        description: "Решение клинических кейсов",
      },
      {
        name: "Практические навыки (OSCE)",
        stage: "semi_final",
        mode: "offline",
        dateFrom: "2025-09-21",
        subjects: ["first_aid", "internal_medicine"],
        examKinds: ["osce"],
        durationMinutes: 120,
        weightPercent: 40,
        description: "Станции практических навыков",
      },
      {
        name: "Командный финал",
        stage: "final",
        mode: "offline",
        dateFrom: "2025-09-23",
        subjects: ["internal_medicine", "surgery", "pediatrics"],
        examKinds: ["case", "team_bowl"],
        durationMinutes: 180,
        weightPercent: 30,
        description: "Командное решение сложных клинических случаев",
      },
    ],
    scoring: {
      ranking: "both",
      totalPoints: 300,
      passingScore: 180,
      notes: "Отдельные рейтинги для индивидуального и командного зачета",
    },
    awards: [
      {
        type: "qualification",
        title: "Отбор на IMSO",
        details: "Лучшие участники проходят в сборную для международной олимпиады",
        qualifiesFor: "International Medical Students Olympiad",
      },
      {
        type: "scholarship",
        title: "Стипендия на обучение",
        details: "Стипендия на семестр обучения за рубежом",
        monetaryAmount: 5000,
        currency: "EUR",
      },
      {
        type: "gold",
        title: "Золотая медаль",
        details: "Индивидуальный и командный зачет",
      },
    ],
    maxParticipants: 120,
    currentParticipants: 89,
    maxTeams: 30,
    registrationRequired: true,
    registrationLink: "https://medical-olympiad.org/register",
    registrationOpenAt: "2025-09-01",
    registrationCloseAt: "2025-09-01",
    documentsRequired: [
      "Справка о зачислении",
      "Академическая справка",
      "Рекомендация от кафедры",
      "Медицинская справка",
    ],
    price_type: "paid",
    price: 8000,
    currency: "RUB",
    hostOrganization: "СПбГМУ им. И.П. Павлова",
    venueName: "Клинический центр",
    jury: [
      {
        name: "Prof. Dr. Schmidt",
        role: "International Chair",
        affiliation: "University of Vienna",
      },
      {
        name: "Профессор Сидоров В.И.",
        role: "Национальный координатор",
        affiliation: "СПбГМУ им. И.П. Павлова",
      },
    ],
    sponsors: ["Медицинская компания Р-Фарм", "Фонд развития медицинского образования"],
    logistics: {
      accommodationProvided: true,
      travelReimbursed: "none",
      mealsProvided: true,
      visaSupport: true,
      notes: "Помощь в оформлении виз для иностранных участников",
    },
    docs: {
      rulesUrl: "https://medical-olympiad.org/rules.pdf",
      syllabusUrl: "https://medical-olympiad.org/curriculum.pdf",
      pastPapersUrl: "https://medical-olympiad.org/archive",
      registrationGuideUrl: "https://medical-olympiad.org/guide.pdf",
    },
    categories: ["medical", "educational"],
    targetAudience: ["students", "specialists"],
    language: "multi",
    level: "Международная",
    participationFormat: "Индивидуальное и командное",
    registrationDeadline: "2025-09-01",
    registrationFee: 8000,
    previewImage: "/5.png"
  },
]

export const getAllMockAnnouncements = () => [
  ...mockConferences,
  ...mockWebinars,
  ...mockMasterClasses,
  ...mockVacancies,
  ...mockOlympiads,
]

export const getMockAnnouncementById = (id: string) => {
  return getAllMockAnnouncements().find((announcement) => announcement.id === id)
}
