import type { Conference, Webinar, MasterClass } from "./index"

export const mockConferences: (Conference & { id: string })[] = [
  {
    id: "conf-1",
    type: "Conference",
    title: "Международная конференция по кардиологии 2024",
    description:
      "Ведущие кардиологи мира представят последние достижения в области диагностики и лечения сердечно-сосудистых заболеваний. Обсуждение инновационных методов лечения, новых препаратов и технологий.",
    organizerName: "Российское кардиологическое общество",
    organizerId: "543534553",
    activeFrom: "2024-03-15",
    activeTo: "2024-03-17",
    status: "published",
    location: {
      address: 'Конгресс-холл "Крокус Экспо"',
      city: "Москва",
    },
    format:"offline",
    contactInfo: {
      email: "info@cardio-conf.ru",
      phone: "+7 (495) 123-45-67",
      website: "https://cardio-conf.ru",
    },
    tags: ["кардиология", "медицина", "конференция", "инновации"],
    viewsCount: 1250,
    isPromoted: true,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-02-01T15:30:00Z",
    speakers: [
      {
        userId: "speaker-1",
        name: "Профессор Иванов А.В.",
        eventRole: "Главный докладчик",
        status: "confirmed",
      },
      {
        userId: "speaker-2",
        name: "Доктор Петрова М.С.",
        eventRole: "Модератор секции",
        status: "confirmed",
      },
    ],
    program: "День 1: Диагностика ИБС\nДень 2: Современные методы лечения\nДень 3: Профилактика и реабилитация",
    registrationRequired: true,
    registrationLink: "https://cardio-conf.ru/register",
    maxParticipants: 500,
    price_type: "paid",
    currentParticipants: 342,
    price: 15000,
    currency: "RUB",
    categories: ["medical"],
    targetAudience: ["doctors", "specialists", 'students', 'researchers'],
    language: "ru",
    certificates: true,
    cmeCredits: 24,
  },
  {
    id: "conf-2",
    type: "Conference",
    title: "Саммит цифрового здравоохранения 2024",
    description:
      "Международный саммит по цифровому здравоохранению. Обсуждение применения ИИ в медицине, телемедицины, цифровых биомаркеров и персонализированной медицины.",
    organizerName: "TechMed International",
    organizerId: "543534553gdf",
    activeFrom: "2024-04-20",
    activeTo: "2024-04-21",
    status: "published",
    location: {
      address: 'Отель "Метрополь"',
      city: "Санкт-Петербург",
    },
    format:"hybrid",
    contactInfo: {
      email: "contact@digitalhealthsummit.com",
      website: "https://digitalhealthsummit.com",
    },
    tags: ["цифровая медицина", "ИИ", "телемедицина", "инновации"],
    viewsCount: 890,
    isPromoted: false,
    createdAt: "2024-01-20T14:00:00Z",
    updatedAt: "2024-02-10T09:15:00Z",
    speakers: [
      {
        userId: "speaker-3",
        name: "Dr. Sarah Johnson",
        eventRole: "Ключевой докладчик",
        status: "confirmed",
      },
    ],
    program: "ИИ в здравоохранении, тренды телемедицины, цифровые биомаркеры",
    registrationRequired: true,
    registrationLink: "https://digitalhealthsummit.com/register",
    maxParticipants: 300,
    price_type: "free",
    currentParticipants: 156,
    price: 25000,
    currency: "RUB",
    categories: ["medical", "it"],
    targetAudience: ["doctors", "specialists", "researchers"],
    language: "multi",
    certificates: true,
    cmeCredits: 16,
  },
]

export const mockWebinars: (Webinar & { id: string })[] = [
  {
    id: "webinar-1",
    type: "Webinar",
    title: "Основы машинного обучения в медицине",
    description:
      "Практический вебинар для медицинских работников о применении машинного обучения в диагностике. Разберем реальные кейсы использования ИИ в радиологии и патологии.",
    organizerName: "AI Medical Academy",
    organizerId: "5435343",
    activeFrom: "2024-03-25",
    status: "published",
    format: "online",
    contactInfo: {
      email: "support@aimedacademy.ru",
      website: "https://aimedacademy.ru",
    },
    tags: ["машинное обучение", "ИИ", "медицина", "диагностика"],
    viewsCount: 567,
    isPromoted: true,
    createdAt: "2024-02-01T12:00:00Z",
    updatedAt: "2024-02-15T16:45:00Z",
    speakers: [
      {
        userId: "speaker-4",
        name: "Кандидат наук Сидоров В.П.",
        eventRole: "Ведущий эксперт",
        status: "confirmed",
      },
    ],
    platform: "zoom",
    platformDetails: {
      meetingId: "123-456-789",
      joinUrl: "https://zoom.us/j/123456789",
    },
    isRecorded: true,
    recordingAvailableUntil: "2024-04-25",
    participantLimit: 100,
    registrationLink: "https://aimedacademy.ru/webinar-ml",
    price_type: "paid",
    price: 3000,
    currency: "RUB",
    categories: ["medical", "it"],
    targetAudience: ["doctors", "specialists"],
    language: "ru",
    duration: 120,
    prerequisites: "Базовые знания статистики и работы с компьютером",
    materials: ["Презентация", "Практические задания", "Список литературы"],
  },
  {
    id: "webinar-2",
    type: "Webinar",
    title: "Современные подходы к лечению диабета",
    description:
      "Обзор новейших методов лечения сахарного диабета 2 типа. Обсуждение персонализированной терапии, новых препаратов и технологий мониторинга.",
    organizerName: "Эндокринологическое общество России",
    organizerId: "534553",
    activeFrom: "2024-04-10",
    status: "published",
    format:"online",
    contactInfo: {
      email: "webinars@endocrin.ru",
      phone: "+7 (495) 987-65-43",
    },
    tags: ["диабет", "эндокринология", "лечение", "инновации"],
    viewsCount: 423,
    isPromoted: false,
    createdAt: "2024-02-05T09:30:00Z",
    updatedAt: "2024-02-20T11:20:00Z",
    speakers: [
      {
        userId: "speaker-5",
        name: "Профессор Козлова Е.А.",
        eventRole: "Главный эксперт",
        status: "confirmed",
      },
    ],
    platform: "teams",
    isRecorded: true,
    recordingLink: "https://endocrin.ru/recordings/diabetes-2024",
    recordingAvailableUntil: "2024-05-10",
    participantLimit: 200,
    registrationLink: "https://endocrin.ru/webinar-diabetes",
    price_type: "free",
    price: 0,
    currency: "RUB",
    categories: ["medical"],
    targetAudience: ["doctors", "specialists"],
    language: "ru",
    duration: 90,
    prerequisites: "Медицинское образование",
    materials: ["Клинические рекомендации", "Алгоритмы лечения"],
  },
]

export const mockMasterClasses: (MasterClass & { id: string })[] = [
  {
    id: "masterclass-1",
    type: "Masterclass",
    title: "Практический курс по УЗИ сердца",
    description:
      "Интенсивный практический мастер-класс по эхокардиографии. Отработка навыков на современном оборудовании под руководством опытных специалистов.",
    organizerName: 'Центр ультразвуковой диагностики "Эксперт"',
    organizerId: "543fs",
    activeFrom: "2024-03-30",
    activeTo: "2024-03-31",
    status: "published",
    location: {
      address: 'Учебный центр "МедПрактик"',
      city: "Москва",
    },
    format:"offline",
    contactInfo: {
      email: "masterclass@uzi-expert.ru",
      phone: "+7 (495) 555-12-34",
      website: "https://uzi-expert.ru",
    },
    tags: ["УЗИ", "эхокардиография", "практика", "диагностика"],
    viewsCount: 234,
    isPromoted: true,
    createdAt: "2024-01-25T13:15:00Z",
    updatedAt: "2024-02-12T10:30:00Z",
    instructor: {
      userId: "instructor-1",
      name: "Доктор медицинских наук Волков А.И.",
      bio: "Ведущий специалист по ультразвуковой диагностике, стаж 20+ лет",
      credentials: ["Доктор медицинских наук", "Профессор кафедры лучевой диагностики"],
    },
    skillLevel: "intermediate",
    maxParticipants: 12,
    currentParticipants: 8,
    registrationLink: "https://endocrin.ru/webinar-diabetes",
    price_type: "paid",
    price: 35000,
    currency: "RUB",
    materials: ["Методические пособия", "Атлас УЗИ-изображений"],
    equipment: ["УЗИ-аппараты экспертного класса", "Фантомы для обучения"],
    duration: 16,
    categories: ["medical"],
    prerequisites: "Медицинское образование, базовые знания УЗИ",
    certificates: true,
    handsOn: true,
    groupWork: true,
  },
  {
  id: "masterclass-2",
  type: "Masterclass",
  title: "Практический курс по лапароскопической хирургии",
  description:
    "Интенсивный мастер-класс с отработкой базовых лапароскопических навыков на тренажёрах: работа инструментами в ограниченном пространстве, координация «глаз–рука», наложение внутриполостных узлов, гемостаз и разбор типичных осложнений.",
  organizerName: 'Симуляционный центр клинических навыков "МедСим"',
  organizerId: "5213563",
  activeFrom: "2024-04-15",
  activeTo: "2024-04-16",
  status: "published",
  location: {
    address: 'Симуляционный центр "МедСим"',
    city: "Москва",
  },
  format:"offline",
  contactInfo: {
    email: "training@medsim.ru",
    website: "https://medsim.ru",
  },
  tags: ["лапароскопия", "хирургия", "симуляционный тренинг", "операционный блок"],
  viewsCount: 189,
  isPromoted: false,
  createdAt: "2024-02-10T11:45:00Z",
  updatedAt: "2024-02-25T14:20:00Z",
  instructor: {
    userId: "instructor-2",
    name: "К.м.н. Николаев М.А.",
    bio: "Лапароскопический хирург, 8+ лет операционного стажа, преподаватель симуляционного тренинга",
    credentials: ["Кандидат медицинских наук", "Врач-хирург высшей категории"],
  },
  speakers: [
    {
      userId: "speaker-6",
      name: "Профессор Смирнов А.А.",
      eventRole: "Приглашённый эксперт",
      status: "confirmed",
    },
    {
      userId: "speaker-7",
      name: "Орлова Н.В.",
      eventRole: "Эксперт по анестезиологии и ERAS",
      status: "pending",
    },
  ],
  skillLevel: "intermediate",
  maxParticipants: 16,
  currentParticipants: 12,
  registrationLink: "https://medsim.ru/courses/laparoscopic-skills",
  price_type: "paid",
  price: 25000,
  currency: "RUB",
  materials: ["Методическое пособие", "Чек-листы навыков", "Видеозаписи операций"],
  equipment: [
    "Лапароскопические тренажёры (box trainer)",
    "Видеостойка",
    "Набор лапароскопических инструментов",
    "Электрохирургический симулятор"
  ],
  duration: 16,
  categories: ["medical"],
  prerequisites: "Хирургическое образование или обучение в ординатуре по хирургии",
  certificates: true,
  handsOn: true,
  groupWork: true,
}
]

export const getAllMockAnnouncements = () => [...mockConferences, ...mockWebinars, ...mockMasterClasses]

export const getMockAnnouncementById = (id: string) => {
  return getAllMockAnnouncements().find((announcement) => announcement.id === id)
}
