import type {
  Conference,
  Webinar,
  Course,
  MasterClass,
  Vacancy,
  Internship,
} from "../../../entities/announcement/model/index"

export const mockRecommendedAnnouncements: (Conference | Webinar | Course | MasterClass | Vacancy | Internship)[] = [
  // вебинара
  {
    title: "Современные методы диагностики в кардиологии",
    description: "Обзор новейших технологий диагностики сердечно-сосудистых заболеваний",
    organizer: "НИИ кардиологии",
    activeFrom: "2024-06-15",
    activeTo: "2024-06-15",
    status: "published",
    type: "webinar",
    location: { type: "online" },
    contactInfo: { email: "info@cardio.ru" },
    tags: ["кардиология", "диагностика"],
    viewsCount: 1250,
    isPromoted: true,
    createdAt: "2024-01-15",
    updatedAt: "2024-01-20",
    speakers: [],
    platform: "zoom",
    isRecorded: true,
    price: 0,
    currency: "RUB",
    categories: ["medical", "science"],
    targetAudience: ["doctors"],
    language: "ru",
    duration: 120,
  },
  {
    title: "Курс повышения квалификации по веб-разработке",
    description: "Современные подходы к разработке веб-приложений на React и Node.js",
    organizer: "IT Academy",
    activeFrom: "2024-07-10",
    activeTo: "2024-07-10",
    status: "published",
    type: "webinar",
    location: { type: "online" },
    contactInfo: { email: "info@itacademy.ru" },
    tags: ["программирование", "веб-разработка"],
    viewsCount: 890,
    isPromoted: false,
    createdAt: "2024-02-01",
    updatedAt: "2024-02-05",
    speakers: [],
    platform: "teams",
    isRecorded: true,
    price: 2500,
    currency: "RUB",
    categories: ["it", "educational"],
    targetAudience: ["doctors"],
    language: "ru",
    duration: 90,
  },
  // мастер-класса
  {
    title: "Мастер-класс по роботической хирургии da Vinci",
    description: "Практические навыки работы с роботической системой da Vinci",
    organizer: "Центр роботической хирургии",
    activeFrom: "2024-08-20",
    activeTo: "2024-08-20",
    status: "published",
    type: "masterclass",
    location: { type: "offline", city: "Москва" },
    contactInfo: { email: "info@surgery.ru" },
    tags: ["хирургия", "роботы"],
    viewsCount: 567,
    isPromoted: true,
    createdAt: "2024-03-01",
    updatedAt: "2024-03-05",
    instructor: {
      userId: "instructor1",
      name: "Проф. Иванов И.И.",
      bio: "Ведущий специалист по роботической хирургии",
      credentials: ["Доктор медицинских наук", "Профессор"],
    },
    skillLevel: "advanced",
    maxParticipants: 20,
    currentParticipants: 15,
    price: 25000,
    currency: "RUB",
    materials: ["Хирургические инструменты", "Защитная одежда"],
    equipment: ["Система da Vinci", "Симуляторы"],
    duration: 8,
    categories: ["medical"],
    certificate: true,
    handsOn: true,
    groupWork: false,
  },
  {
    title: "Мастер-класс по эндоскопической хирургии",
    description: "Современные техники минимально инвазивной хирургии",
    organizer: "Центр эндоскопии",
    activeFrom: "2024-09-15",
    activeTo: "2024-09-15",
    status: "published",
    type: "masterclass",
    location: { type: "hybrid", city: "Санкт-Петербург" },
    contactInfo: { email: "info@endoscopy.ru" },
    tags: ["эндоскопия", "хирургия"],
    viewsCount: 423,
    isPromoted: false,
    createdAt: "2024-04-01",
    updatedAt: "2024-04-05",
    instructor: {
      userId: "instructor2",
      name: "Д-р Петров П.П.",
      bio: "Специалист по эндоскопической хирургии",
      credentials: ["Кандидат медицинских наук"],
    },
    skillLevel: "intermediate",
    maxParticipants: 15,
    currentParticipants: 8,
    price: 18000,
    currency: "RUB",
    materials: ["Медицинская форма"],
    equipment: ["Эндоскопическое оборудование"],
    duration: 6,
    categories: ["medical"],
    certificate: true,
    handsOn: true,
    groupWork: true,
  },
  // конференции
  {
    title: "Международный форум по репродуктивной медицине",
    description: "Ведущее мероприятие в области репродуктивной медицины с участием международных экспертов",
    organizer: "Центр репродукции",
    activeFrom: "2024-10-20",
    activeTo: "2024-10-22",
    status: "published",
    type: "conference",
    location: { type: "offline", city: "Москва" },
    contactInfo: { email: "info@repro.ru" },
    tags: ["репродукция", "гинекология"],
    viewsCount: 1890,
    isPromoted: true,
    createdAt: "2024-05-01",
    updatedAt: "2024-05-05",
    speakers: [],
    registrationRequired: true,
    price_type: "paid",
    currentParticipants: 145,
    price: 15000,
    currency: "RUB",
    categories: ["medical"],
    targetAudience: ["doctors"],
    language: "ru",
    certificates: true,
  },
  {
    title: "Конференция по инновациям в онкологии",
    description: "Новейшие достижения в диагностике и лечении онкологических заболеваний",
    organizer: "НИИ онкологии",
    activeFrom: "2024-11-10",
    activeTo: "2024-11-12",
    status: "published",
    type: "conference",
    location: { type: "hybrid", city: "Санкт-Петербург" },
    contactInfo: { email: "info@oncology.ru" },
    tags: ["онкология", "инновации"],
    viewsCount: 1456,
    isPromoted: false,
    createdAt: "2024-06-01",
    updatedAt: "2024-06-05",
    speakers: [],
    registrationRequired: true,
    price_type: "paid",
    currentParticipants: 89,
    price: 12000,
    currency: "RUB",
    categories: ["medical"],
    targetAudience: ["doctors"],
    language: "ru",
    certificates: true,
  },
  // стажировка
  {
    title: "Стажировка в отделении кардиохирургии",
    description: "3-месячная стажировка для молодых специалистов в ведущем кардиохирургическом центре",
    organizer: "НМИЦ кардиологии",
    activeFrom: "2024-09-01",
    activeTo: "2024-11-30",
    status: "published",
    type: "internship",
    location: { type: "offline", city: "Москва" },
    contactInfo: { email: "internship@cardio.ru" },
    tags: ["стажировка", "кардиохирургия"],
    viewsCount: 678,
    isPromoted: true,
    createdAt: "2024-04-15",
    updatedAt: "2024-04-20",
    department: "Кардиохирургия",
    supervisor: {
      userId: "supervisor1",
      name: "Проф. Сидоров С.С.",
      position: "Заведующий отделением",
    },
    duration: {
      months: 3,
      startDate: "2024-09-01",
      endDate: "2024-11-30",
    },
    requirements: {
      education: "Высшее медицинское образование",
      skills: ["Базовые хирургические навыки", "Знание анатомии"],
      languages: ["Русский"],
    },
    responsibilities: ["Участие в операциях", "Ведение пациентов", "Научная работа"],
    benefits: ["Сертификат", "Рекомендательное письмо", "Опыт работы"],
    isPaid: true,
    stipend: 30000,
    currency: "RUB",
    maxInterns: 5,
    currentInterns: 2,
    applicationDeadline: "2024-08-15",
    remote: false,
    partTime: false,
    categories: ["medical"],
  },
  // курс
  {
    title: "Курс повышения квалификации по нейрохирургии",
    description: "Комплексный курс для специалистов по современным методам нейрохирургии",
    organizer: "РМАНПО",
    activeFrom: "2024-10-01",
    activeTo: "2024-12-15",
    status: "published",
    type: "course",
    location: { type: "hybrid", city: "Москва" },
    contactInfo: { email: "courses@rmanpo.ru" },
    tags: ["нейрохирургия", "курсы"],
    viewsCount: 892,
    isPromoted: false,
    createdAt: "2024-05-10",
    updatedAt: "2024-05-15",
    instructors: [],
    modules: [
      {
        title: "Основы нейрохирургии",
        description: "Анатомия и физиология нервной системы",
        duration: 40,
        materials: ["Учебник", "Атлас"],
      },
      {
        title: "Современные методы диагностики",
        description: "МРТ, КТ, нейронавигация",
        duration: 30,
        materials: ["Методические пособия"],
      },
    ],
    totalHours: 144,
    accredited: true,
    accreditationBody: "Минздрав РФ",
    credits: 36,
    skillLevel: "advanced",
    maxParticipants: 25,
    currentParticipants: 18,
    price: 45000,
    currency: "RUB",
    format: "hybrid",
    schedule: {
      startDate: "2024-10-01",
      endDate: "2024-12-15",
      sessionsPerWeek: 2,
      sessionDuration: 4,
    },
    prerequisites: ["Высшее медицинское образование", "Специализация по хирургии"],
    targetAudience: ["Нейрохирурги", "Хирурги"],
    categories: ["medical"],
    certificate: true,
    diploma: false,
    assessments: true,
    practicalWork: true,
  },
  //вакансия
  {
    title: "Врач-кардиолог в частную клинику",
    description: "Требуется опытный врач-кардиолог для работы в современной частной клинике",
    organizer: "Медицинский центр 'Здоровье'",
    activeFrom: "2024-06-01",
    activeTo: "2024-08-31",
    status: "published",
    type: "vacancy",
    location: { type: "offline", city: "Москва" },
    contactInfo: { email: "hr@health-center.ru", phone: "+7 (495) 123-45-67" },
    tags: ["вакансия", "кардиология"],
    viewsCount: 1234,
    isPromoted: true,
    createdAt: "2024-05-20",
    updatedAt: "2024-05-25",
    position: "Врач-кардиолог",
    department: "Кардиологическое отделение",
    employmentType: "full-time",
    workFormat: "office",
    salary: {
      min: 150000,
      max: 250000,
      currency: "RUB",
      negotiable: true,
    },
    requirements: {
      education: "Высшее медицинское образование",
      experience: "От 5 лет",
      skills: ["ЭКГ", "ЭхоКГ", "Холтер", "Нагрузочные тесты"],
      certifications: ["Сертификат кардиолога"],
      languages: ["Русский"],
    },
    responsibilities: [
      "Консультирование пациентов",
      "Проведение диагностических процедур",
      "Назначение лечения",
      "Ведение медицинской документации",
    ],
    benefits: ["Официальное трудоустройство", "ДМС", "Обучение за счет компании", "Современное оборудование"],
    schedule: "5/2, с 9:00 до 18:00",
    hiringManager: {
      name: "Иванова А.В.",
      position: "HR-менеджер",
    },
    applicationDeadline: "2024-08-31",
    categories: ["medical", "business"],
    urgent: false,
    featured: true,
  },
]

export const mockAllAnnouncements = mockRecommendedAnnouncements
