import type { ConferenceWithManagement } from "@/entities/announcement/model/conference-management"

// Конференция с этапами
const conferenceWithStages: ConferenceWithManagement = {
  id: "conf-stages-1",
  title: "Международная конференция по кардиологии 2025",
  description:
    "Ведущие кардиологи мира представят последние достижения в области диагностики и лечения сердечно-сосудистых заболеваний.",
  organizerName: "Российское кардиологическое общество",
  activeFrom: "2025-11-29",
  activeTo: "2025-12-17",
  status: "published",
  location: {
    address: 'Конгресс-холл "Крокус Экспо"',
    city: "Москва",
  },
  format: "offline",
  maxParticipants: 500,
  currentParticipants: 12,
  previewImage: "/1.png",
  stages: [
    {
      id: "stage-1",
      name: "Отборочный тур",
      date: "2025-11-29",
      maxParticipants: 50,
      order: 1,
    },
    {
      id: "stage-2",
      name: "Полуфинал",
      date: "2025-12-05",
      maxParticipants: 20,
      order: 2,
    },
    {
      id: "stage-3",
      name: "Финал",
      date: "2025-12-17",
      maxParticipants: 10,
      order: 3,
    },
  ],
  applications: [
    {
      id: "app-1",
      conferenceId: "conf-stages-1",
      participantName: "Иванов Петр Сергеевич",
      participantEmail: "ivanov@example.com",
      talkTitle: "Инновационные методы диагностики ИБС",
      abstract:
        "В докладе рассматриваются современные подходы к ранней диагностике ишемической болезни сердца с использованием искусственного интеллекта.",
      attachedFiles: [
        {
          id: "file-1",
          name: "presentation.pdf",
          url: "/files/presentation.pdf",
          size: 2048000,
          type: "application/pdf",
        },
      ],
      submittedAt: "2025-10-15T10:30:00Z",
      status: "pending",
    },
    {
      id: "app-2",
      conferenceId: "conf-stages-1",
      participantName: "Смирнова Анна Викторовна",
      participantEmail: "smirnova@example.com",
      talkTitle: "Применение биомаркеров в кардиологии",
      abstract:
        "Обзор современных биомаркеров для оценки риска сердечно-сосудистых заболеваний и их клиническое применение.",
      attachedFiles: [
        {
          id: "file-2",
          name: "abstract.docx",
          url: "/files/abstract.docx",
          size: 512000,
          type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        },
      ],
      submittedAt: "2025-10-16T14:20:00Z",
      status: "pending",
    },
    {
      id: "app-3",
      conferenceId: "conf-stages-1",
      participantName: "Козлов Дмитрий Александрович",
      participantEmail: "kozlov@example.com",
      talkTitle: "Телемедицина в кардиологической практике",
      abstract:
        "Опыт внедрения телемедицинских технологий для мониторинга пациентов с хроническими заболеваниями сердца.",
      attachedFiles: [],
      submittedAt: "2025-10-17T09:15:00Z",
      status: "pending",
    },
  ],
  participants: [
    {
      id: "part-1",
      conferenceId: "conf-stages-1",
      applicationId: "app-old-1",
      participantName: "Волков Алексей Иванович",
      participantEmail: "volkov@example.com",
      talkTitle: "Современные методы реваскуляризации миокарда",
      currentStageId: "stage-1",
      isWinner: false,
      approvedAt: "2025-10-10T12:00:00Z",
    },
    {
      id: "part-2",
      conferenceId: "conf-stages-1",
      applicationId: "app-old-2",
      participantName: "Морозова Елена Петровна",
      participantEmail: "morozova@example.com",
      talkTitle: "Профилактика внезапной сердечной смерти",
      currentStageId: "stage-1",
      isWinner: false,
      approvedAt: "2025-10-11T15:30:00Z",
    },
    {
      id: "part-3",
      conferenceId: "conf-stages-1",
      applicationId: "app-old-3",
      participantName: "Соколов Игорь Владимирович",
      participantEmail: "sokolov@example.com",
      talkTitle: "Антикоагулянтная терапия при фибрилляции предсердий",
      currentStageId: "stage-2",
      isWinner: false,
      approvedAt: "2025-10-12T10:45:00Z",
    },
    {
      id: "part-4",
      conferenceId: "conf-stages-1",
      applicationId: "app-old-4",
      participantName: "Новикова Ольга Сергеевна",
      participantEmail: "novikova@example.com",
      talkTitle: "Гендерные особенности сердечно-сосудистых заболеваний",
      currentStageId: "stage-2",
      isWinner: false,
      approvedAt: "2025-10-13T11:20:00Z",
    },
    {
      id: "part-5",
      conferenceId: "conf-stages-1",
      applicationId: "app-old-5",
      participantName: "Лебедев Сергей Николаевич",
      participantEmail: "lebedev@example.com",
      talkTitle: "Искусственный интеллект в интерпретации ЭКГ",
      currentStageId: "stage-3",
      isWinner: true,
      approvedAt: "2025-10-14T09:00:00Z",
    },
    {
      id: "part-6",
      conferenceId: "conf-stages-1",
      applicationId: "app-old-6",
      participantName: "Павлова Мария Андреевна",
      participantEmail: "pavlova@example.com",
      talkTitle: "Реабилитация после инфаркта миокарда",
      currentStageId: "stage-3",
      isWinner: true,
      approvedAt: "2025-10-15T08:30:00Z",
    },
  ],
}

// Конференция без этапов
const conferenceWithoutStages: ConferenceWithManagement = {
  id: "conf-no-stages-1",
  title: "Симпозиум по неврологии 2025",
  description: "Обсуждение актуальных вопросов диагностики и лечения неврологических заболеваний.",
  organizerName: "Российское общество неврологов",
  activeFrom: "2025-12-10",
  activeTo: "2025-12-12",
  status: "published",
  location: {
    address: "Медицинский университет им. Сеченова",
    city: "Москва",
  },
  format: "hybrid",
  maxParticipants: 200,
  currentParticipants: 8,
  previewImage: "/2.png",
  stages: undefined,
  applications: [
    {
      id: "app-neuro-1",
      conferenceId: "conf-no-stages-1",
      participantName: "Григорьев Андрей Павлович",
      participantEmail: "grigoriev@example.com",
      talkTitle: "Новые подходы к лечению болезни Паркинсона",
      abstract:
        "Рассмотрение современных методов терапии болезни Паркинсона, включая генную терапию и нейростимуляцию.",
      attachedFiles: [
        {
          id: "file-neuro-1",
          name: "research.pdf",
          url: "/files/research.pdf",
          size: 3072000,
          type: "application/pdf",
        },
      ],
      submittedAt: "2025-11-01T10:00:00Z",
      status: "pending",
    },
    {
      id: "app-neuro-2",
      conferenceId: "conf-no-stages-1",
      participantName: "Федорова Татьяна Михайловна",
      participantEmail: "fedorova@example.com",
      talkTitle: "Диагностика рассеянного склероза на ранних стадиях",
      abstract: "Современные методы ранней диагностики рассеянного склероза с использованием МРТ и биомаркеров.",
      attachedFiles: [],
      submittedAt: "2025-11-02T14:30:00Z",
      status: "pending",
    },
  ],
  participants: [
    {
      id: "part-neuro-1",
      conferenceId: "conf-no-stages-1",
      applicationId: "app-neuro-old-1",
      participantName: "Кузнецов Владимир Олегович",
      participantEmail: "kuznetsov@example.com",
      talkTitle: "Эпилепсия: современные стратегии лечения",
      currentStageId: undefined,
      isWinner: false,
      approvedAt: "2025-10-25T11:00:00Z",
    },
    {
      id: "part-neuro-2",
      conferenceId: "conf-no-stages-1",
      applicationId: "app-neuro-old-2",
      participantName: "Белова Ирина Александровна",
      participantEmail: "belova@example.com",
      talkTitle: "Инсульт: профилактика и реабилитация",
      currentStageId: undefined,
      isWinner: false,
      approvedAt: "2025-10-26T09:30:00Z",
    },
    {
      id: "part-neuro-3",
      conferenceId: "conf-no-stages-1",
      applicationId: "app-neuro-old-3",
      participantName: "Орлов Максим Викторович",
      participantEmail: "orlov@example.com",
      talkTitle: "Нейродегенеративные заболевания: новые горизонты",
      currentStageId: undefined,
      isWinner: true,
      approvedAt: "2025-10-27T10:15:00Z",
    },
  ],
}

export const mockConferences: ConferenceWithManagement[] = [conferenceWithStages, conferenceWithoutStages]

export function getConferenceById(id: string): ConferenceWithManagement | undefined {
  return mockConferences.find((conf) => conf.id === id)
}
